### ISSUE TITLE
Simple example error

### ISSUE THREAD

**Issue by nyckmaia** [steven-varga/h5cpp#37]
Hi, I copy and paste this short example source-code in a new Qt C++ console project (using C++17)

**Code example link:** http://h5cpp.org/eigen3_8cpp-example.html

**And I got these compile time errors:**
![image](https://user-images.githubusercontent.com/4555404/67038352-98a33f80-f0f5-11e9-8b85-4df1474b1448.png)

So I tryed another simple Eigen example:
```
#include <QCoreApplication>
#include <iostream>
#include <Eigen/Dense> // must include Eigen before <h5cpp/core>
#include <h5cpp/all>

using Eigen::MatrixXd;

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    MatrixXd m(2,2);
    m(0,0) = 3;
    m(1,0) = 2.5;
    m(0,1) = -1;
    m(1,1) = m(1,0) + m(0,1);

    h5::fd_t fd = h5::create("some_file.h5", H5F_ACC_TRUNC);
    h5::write(fd,"/result", m);

    return a.exec();
}
```
And I got a lot of **compilation errors again:**
![image](https://user-images.githubusercontent.com/4555404/67038563-0d767980-f0f6-11e9-921d-c85233938e93.png)

**What I have to do?**

**Comment by ChrisDrozdowski** [comment]
Hi,
Which compiler are you using? I ask because if you are using a VC++ (VS 2017 or later), there is a VC++ specific branch you may wish to try.

In that branch, the examples were not ported to VC++ but left as they are in the master branch to minimize the amount of changes to keep up with. However I have a repo with many (not al) examples ported to VC++. In that repo, for better or worse, all examples are projects are combined under a single VS Solution.

It is available here: https://github.com/ChrisDrozdowski/h5cpp-msvc-examples

**Comment by nyckmaia** [comment]
Ok, I downloaded the new repo and opened in my Visual Studio 2019 Enterprise.
So I tryed to compile only the "Basics" project.
I check the HDF5 include path, and it is correct, **but I got these errors:**
![image](https://user-images.githubusercontent.com/4555404/67044279-49174080-f102-11e9-9171-f175cfef5314.png)

**My system:**

- Windows 10 x64
- Visual Studio 2019 Enterprise (16.3.4)

**Comment by steven-varga** [comment]
Hi Chris is the one keeping up with the windows branch - as I am still busy to add features: sparse matrix, full stl, arbitrary classes.

Be certain to [check out the relevant branch](https://github.com/steven-varga/h5cpp/tree/vs2017-windows) or use g++ or clang to compile the IO related routines. Make sure to use the latest [HDF5 CAPI release](https://www.hdfgroup.org/downloads/hdf5/) or better, the one that Chris is working with.

**error: comrpess2**
Below is the original header file, and is an internal of HDF5 CAPI:
`int compress2(Bytef * dest, uLongf * destLen, const Bytef * source, uLong sourceLen, int level);` 

Can you try to remove chunk and gzip compression and see if your problem persists?
```   
{ // CREATE - WRITE
        Matrix<short> M(2,3);                                       // create a matrix
        h5::fd_t fd = h5::create("linalg.h5",H5F_ACC_TRUNC);    // and a file
        h5::ds_t ds = h5::create<short>(fd,"create then write"
                ,h5::current_dims{10,20}
                ,h5::max_dims{10,H5S_UNLIMITED}
                /*,h5::chunk{2,3} | h5::fill_value<short>{3} |  h5::gzip{9}*/

        );
        h5::write( ds,  M, h5::offset{2,2}, h5::stride{1,3}  );
}
```

**Comment by ChrisDrozdowski** [comment]
Hi Nyckmaia,

Why don't we carry on with this by opening an issue on my examples repo I mentioned previously. 

In the mean time, make sure that the H5CPP source files get copied into the h5cpp folder in the solution. They are not there by default. When I test, I get similar errors when the files aren't there for me.

If it turns out to require Steve's attention, we can come back here.

~Chris

**Comment by steven-varga** [comment]
Problem has been fixed by placing the `h5cpp` include files into correct directory. (Thanks Chris!)  

All header only systems the include files must be reachable to the compiler, and may require manual copying of `h5cpp` directory on Windows OS into your project directory. The project is MIT licensed: shipping the header files with your projects is OK. In fact it is encouraged to prevent version mismatch due to the heavy development of the project.
