### ISSUE TITLE
Half-precision float support?

### ISSUE THREAD

**Issue by jyhengcoder** [steven-varga/h5cpp#40]
Hi! I want to know, is there any methods for me to use fp16 in hdf5-C++?

I intend to use the Half precision floating-point format for storing data that do not need as much precision in order to save space. So does this code support half-precision float storage?

I know that h5py provides an option to store data as fp16, like this:
```
file.create_dataset(key, data=data,  dtype = np.float16)
```
But no  predefined type provided for fp16 storage on the official documentation of hdf5 for C++ , linking here https://support.hdfgroup.org/HDF5/doc1.8/RM/PredefDTypes.html. And I found hdf5 has an C interface named H5Tset_precision,  so does this interface have a corresponding implementation in h5cpp?

**Comment by steven-varga** [comment]
**short:** What library do you use? -- if this can wait a day I will add native support for the library. Can you tell me more of the usage pattern? AFAIK BLAS/LAPACK doesn't support half precision but cuBLAS does.

**long:** All CAPI functions may be called on the matching H5CPP descriptor, there is a controlled conversion mechanism to allow [seamless interop](http://sandbox.h5cpp.org/architecture/#resource-handles-and-capi-interop) between the two systems. In fact the two are binary compatible -- or almost because of [this bug](https://github.com/steven-varga/hdf5_custom_prop). Since it's been fixed, the upcoming version will revert to full binary compatibility --  

Similarly to HDF5 CAPI the source code is organised by interface modules.  In this case the  `H5Tall.hpp` contains the relevant code to control type mapping. In your case an additional map to FP16 type needs to be added. The modification is 1 or 4 lines depending the situation and rather trivial to do. Since there is code block on my laptop not yet published, it is suggested to follow **short** version. Send me the information and allow me some time to fix this.

best wishes: steve

**Comment by jyhengcoder** [comment]
Sorry for late reply! @steven-varga 
Have you added support for float16? And if done, can you give me an example for how to apply it to my own code?

**Comment by steven-varga** [comment]
Happy Holidays!
You still have to name the  IEEE 754-based half-precision floating-point library you are using.

**Comment by steven-varga** [comment]
commit 829f06b96cbed40d8b57e3271b8698f72249c867  adds [IEEE 754 half-precision binary floating-point format](https://en.wikipedia.org/wiki/Half-precision_floating-point_format): binary16  based on [half  2.1](http://half.sourceforge.net/index.html) header only library by [Christian Rau](https://sourceforge.net/u/rauy/profile/)

Make certain to include `half.hpp` before `<h5cpp/core>` to activate the type descriptors. Currently typed pointers and `std::vector<half_float::half>` are supported.  See `examples/half-float`.

**Comment by steven-varga** [comment]
commit 4c7da2d4922f7fabcfd7043e3d60f163998dc84e adds [OpenEXR](https://www.openexr.com/index.html) half float support. Requested on [HDF5 Mailing list](https://forum.hdfgroup.org/t/half-precision-floating-point-format-h5cpp-c/6532/3)
