### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by nyckmaia** [steven-varga/h5cpp#51]
Is there a Windows support?
Can I use this library in the Windows 10 x64 environment?

**Comment by steven-varga** [comment]
The library is header only,  requiring C++17 and linking against HDF5 CLIB and its dependencies `-lhdf5  -lz -ldl -lm`  -- in other words: no HDF5 C++ or high level API is needed.

Now to answer your question, [Chris Drozdowski](https://github.com/ChrisDrozdowski) maintains a [branch for VC2017](https://github.com/ChrisDrozdowski/h5cpp), a Microsoft toolchain, to mitigate the differences between gnu/clang C++lib and ms c++lib. On his github you also [find examples tailored](https://github.com/ChrisDrozdowski/h5cpp-msvc-examples) to MSVC.
As far as compatibility goes: any recent version of gcc, and clang++-6.0 is known to work, beside Chris's VC2017.

If you want compiler assisted reflection -- because it rocks -- you will need to install clang++-6.0 developer version. Or just use a linux within windows or the other way, and install the provided binaries. Currently I don't maintain a windows binary for h5cpp-compiler.

hope it helps.

**Comment by ChrisDrozdowski** [comment]
Hi,

Please _**carefully**_ read through the README.md file for the [h5cpp-msvc-examples](https://github.com/ChrisDrozdowski/h5cpp-msvc-examples) repo **particularly which files need to be placed in subfolders**.

If you follow what I've written, you shouldn't have difficulties.

As of right now, you'll need to use the MSVC compiler. Clang on Windows relies on the MSVC STL which requires a min Clang version 8.0 which is incompatible with h5cpp.

I have used h5cpp to great success on Windows. Feel free to ask any questions.
